theme: jekyll-theme-minimal

title: Overcast for Mac (unofficial)
description: An unofficial macOS desktop application for Overcast.

google_analytics: UA-41066869-1
show_downloads: false

download: https://github.com/nathanbirrell/overcast-macos/releases/latest
version: v0.2.2

github:
  user: nathanbirrell
  repo: overcast-macos
